# makes methods look different based on variable name length
Style/ConditionalAssignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
